baseURL = 'https://nosuchanimaltheband.com/'
locale = 'en-us'
title = 'No Such Animal'
theme = 'no-such-theme'
disableKinds = ["taxonomy","term","section"]
publishDir = 'build'

[outputs]
  home = ['html']
